### ISSUE TITLE
Dist folder not ignored

### ISSUE THREAD

**Issue by angelolamonaca** [Sean-Bradley/Three.js-TypeScript-Boilerplate#14]
Hi, I am using this boilerplate as a basis for my portfolio.

I noticed that in this boilerplate I have to upload the dist folder with the html file and the 3d models to git.
I don't usually load the build folder on git with other projects.
Maybe can we find a better Webpack configuration to avoid this behaviour?
What do you think about it?

**Comment by Sean-Bradley** [comment]
I think you are over complicating what you think it needs to be. You don't even need to use git at all if you don't want to.
See my website where I show lots of ways of working with this structure,
https://sbcode.net/threejs/deploy-prod-intro/

**Comment by Sean-Bradley** [comment]
see https://sean-bradley.github.io/Three.js-TypeScript-Boilerplate/
how did I do this?
I checked out the `cannonjs` branch of this boilerplate
I ran,
`npm install`
`npm build`
`npm install gh-pages --save-dev`
`npx gh-pages -d ./dist/client`
it responded with `published`
I then opened at web browser and visited 
https://sean-bradley.github.io/Three.js-TypeScript-Boilerplate/
![image](https://user-images.githubusercontent.com/6302260/143323645-86d07732-1ab5-4efc-ab61-e4732f646616.png)

**Comment by angelolamonaca** [comment]
Hi, maybe I misplaced my question.
I am studying webpack and I will make my configuration according to my needs.
Thank you so much for the hint :)

**Comment by Sean-Bradley** [comment]
I see, you want your images and models encoded into the final bundle.js. 
I'd try
https://webpack.js.org/guides/asset-modules/
