### ISSUE TITLE
Excellent boilerplate (not an issue)

### ISSUE THREAD

**Issue by john--** [Sean-Bradley/Three.js-TypeScript-Boilerplate#26]
As someone with extensive development experimence but not familiar with three.js, I really wanted a boilerplate I could jump right in with. Other projects on github are overly complex or just a mess. This one is the first that looks nice. 

Good idea on separating out other examples in the other branches.

Everything appears to be kept up to date as well. `npm outdated` shows most packages are pretty much in date.

As a thank you, I've bought your udemy course.

**Comment by Sean-Bradley** [comment]
Cool, thanks,
I try to keep all the code on the website and GitHub no more than a few versions behind.
Some videos can be quite a few versions behind, but I've commented on the website and in the code examples any important differences to be aware of.
