### ISSUE TITLE
How to pass argument in client.ts and get a response

### ISSUE THREAD

**Issue by rahulrajpalhiteshi** [Sean-Bradley/Three.js-TypeScript-Boilerplate#3]
Hi,
Thanks for the awesome boilerplate, I've made an awesome app which will run on the server. Basically I want to pass some parameters to client.ts and with the help of that it will create a animated video of glb. Well my code is ready and working on browser perfectly but, I am unable to specify route in server.ts which will pass an argument to client.ts and get the required response (URL of the saved video).

Please help as I am trying from almost last 7 days.

**Comment by Sean-Bradley** [comment]
Can you describe in more detail what you want to achieve. 
Maybe i already have a good example 
The socketio branch shows communication between client and server using sockets. So does the ballgame branch.
The annotations and bsc5 branches demonstrate downloading data from the server that is used by the client.

**Comment by rahulrajpalhiteshi** [comment]
Hello @Sean-Bradley 
I am trying to make a node app which will record the scene on the server then make a animated video out of it using ffmpeg. The code is working perfectly on the browser but, I am unable to do the same with a headless browser.

Also, my main concern here is that the texture will get updated through a API param and I am unable to pass any data from server.ts to client.ts.

It would be good if you can put some light on this although, the project has gone but your answer will increase my knowledgebase. 

Thanks!

**Comment by Sean-Bradley** [comment]
Server side rendering isnt possible unless your server supports glsl.
There is more discussion here, https://discourse.threejs.org/t/server-side-rendering/10517

I could come up with a solution, but I will only do it if somebody hires me.
