### ISSUE TITLE
mime type

### ISSUE THREAD

**Issue by Mathias-Fuchs** [Sean-Bradley/Three.js-TypeScript-Boilerplate#4]
when I add a typescript file mf.ts to the folder src/client, and
` import * as MF from './mf' `
it into client.ts, it gets build correctly to a file dist/client/mf.js by
`npm run dev`   
but the mimetype of mf.js gets served as text instead of javascript, breaking the rendering of index.html altogether.
How am I supposed to add a typescript file correctly?

**Comment by Sean-Bradley** [comment]
Ive never experienced your problem. See the ballgame branch where i import other ts files. When you figure out your problem, leave a comment what you did that broke your version of the code.

**Comment by Mathias-Fuchs** [comment]
that worked, thanks for the explanation!
